### PR TITLE
Announce the first release

### PR DESCRIPTION
**Pull request by pavel-kirienko**

### CODE REVIEW

**Comment by pavel-kirienko** [comment]
@dimracer seeing as you are unavailable at the moment, I am reassigning it to you. Please merge and tag the release afterward.

**Review by dimracer — APPROVED** [review]

**Comment by dimracer** [comment]
Merging is blocked

**Comment by pavel-kirienko** [comment]
Why?

**Comment by dimracer** [comment]
I'm not authorized to merge this pull request.

**Comment by pavel-kirienko** [comment]
@dimracer Sorry, there were permission configuration issues. They are now fixed but let me merge it myself then while I'm at it.

**Pull request merged**
